name: caddy

services:
  caddy:
    ports:
     - 80:80
    restart: always
    networks:
     - caddy
    image: caddy
    entrypoint: caddy reverse-proxy --from :80 --to 192.168.2.227:3000

networks:
  caddy:
    name: caddy
